import { v4 as uuidv4 } from "uuid";

export const ALL_BRANDS = [
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/1.png`),
    label: "Audi",
    value: "audi",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/2.png`),
    label: "Alfa Romeo",
    value: "alfa_romeo",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/3.png`),
    label: "BMW",
    value: "bmw",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/4.png`),
    label: "Citroen",
    value: "citroen",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/5.png`),
    label: "Cupra",
    value: "cupra",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/6.png`),
    label: "DC",
    value: "dc",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/7.png`),
    label: "DS",
    value: "ds",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/8.png`),
    label: "Fiat",
    value: "fiat",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/9.png`),
    label: "Ford",
    value: "ford",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/10.png`),
    label: "Honda",
    value: "honda",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/11.png`),
    label: "Hyundai",
    value: "hyundai",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/12.png`),
    label: "Jaguar",
    value: "jaguar",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/13.png`),
    label: "Jeep",
    value: "jeep",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/14.png`),
    label: "KIA",
    value: "kia",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/15.png`),
    label: "Land Rover",
    value: "land_rover",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/16.png`),
    label: "Lexus",
    value: "lexus",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/17.png`),
    label: "Mazda",
    value: "mazda",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/18.png`),
    label: "Mercedes-Benz",
    value: "mercedes_benz",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/19.png`),
    label: "Mini",
    value: "mini",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/20.png`),
    label: "Mitsubishi",
    value: "mitsubishi",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/21.png`),
    label: "MG",
    value: "mg",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/22.png`),
    label: "Nissan",
    value: "nissan",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/23.png`),
    label: "Opel",
    value: "opel",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/24.png`),
    label: "Peugeot",
    value: "peugeot",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/25.png`),
    label: "Polestar",
    value: "polestar",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/26.png`),
    label: "Porsche",
    value: "porsche",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/27.png`),
    label: "Renault",
    value: "renault",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/28.png`),
    label: "Seat",
    value: "seat",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/29.png`),
    label: "Skoda",
    value: "skoda",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/30.png`),
    label: "Smart",
    value: "smart",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/31.png`),
    label: "Tesla",
    value: "tesla",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/32.png`),
    label: "Toyota",
    value: "toyota",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/33.png`),
    label: "Volkswagen",
    value: "volkswagen",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/34.png`),
    label: "Volvo",
    value: "volvo",
  },
];
