import { v4 as uuidv4 } from "uuid";

export const ALL_BRANDS = [
 
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/1.png`),
    label: "Audi",
    value: "Audi",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/2.png`),
    label: "Alfa Romeo",
    value: "Alfa Romeo",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/3.png`),
    label: "BMW",
    value: "BMW",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/4.png`),
    label: "Citroen",
    value: "Citroen",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/5.png`),
    label: "Cupra",
    value: "Cupra",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/6.png`),
    label: "DC",
    value: "DC",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/7.png`),
    label: "DS",
    value: "DS",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/8.png`),
    label: "Fiat",
    value: "Fiat",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/9.png`),
    label: "Ford",
    value: "Ford",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/10.png`),
    label: "Honda",
    value: "Honda",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/11.png`),
    label: "Hyundai",
    value: "Hyundai",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/12.png`),
    label: "Jaguar",
    value: "Jaguar",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/13.png`),
    label: "Jeep",
    value: "Jeep",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/14.png`),
    label: "KIA",
    value: "KIA",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/15.png`),
    label: "Land Rover",
    value: "Land Rover",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/16.png`),
    label: "Lexus",
    value: "Lexus",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/17.png`),
    label: "Mazda",
    value: "Mazda",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/18.png`),
    label: "Mercedes-Benz",
    value: "Mercedes-Benz",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/19.png`),
    label: "Mini",
    value: "Mini",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/20.png`),
    label: "Mitsubishi",
    value: "Mitsubishi",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/21.png`),
    label: "MG",
    value: "MG",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/22.png`),
    label: "Nissan",
    value: "Nissan",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/23.png`),
    label: "Opel",
    value: "Opel",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/24.png`),
    label: "Peugeot",
    value: "Peugeot",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/25.png`),
    label: "Polestar",
    value: "Polestar",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/26.png`),
    label: "Porsche",
    value: "Porsche",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/27.png`),
    label: "Renault",
    value: "Renault",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/28.png`),
    label: "Seat",
    value: "Seat",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/29.png`),
    label: "Skoda",
    value: "Skoda",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/30.png`),
    label: "Smart",
    value: "Smart",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/31.png`),
    label: "Tesla",
    value: "Tesla",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/32.png`),
    label: "Toyota",
    value: "Toyota",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/33.png`),
    label: "Volkswagen",
    value: "Volkswagen",
  },
  {
    _id: uuidv4(),
    img: require(`../assets/images/brands/34.png`),
    label: "Volvo",
    value: "Volvo",
  },
];
